# Generated by Django 6.0.4 on 2026-05-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0002_useractivity"),
    ]

    operations = [
        migrations.AddField(
            model_name="querystat",
            name="user_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
